### PR TITLE
feat(config): add vivaldi

### PR DESCRIPTION
**Pull request by cyagon**

### CODE REVIEW

**Comment by guiweber** [comment]
Thanks! Could you add a filter or modify the selector for the x86 version to make sure it doesn't select the x64 link? At the moment this would happen if they change order on the download page.

**Comment by cyagon** [comment]
this seems to work. this happens when i switched the x86 and x86_64 entries:
unbenannt

**Comment by guiweber** [comment]
It might work but I'd feel safer with a filter excluding "x64" in the x86 link for example. That way we're sure the registry will never be updated with a link for the wrong architecture. Thanks.

**Comment by cyagon** [comment]
like this?

```
  "vivaldi": {
    "url": "https://vivaldi.com/download/",
    "updater": {
      "x86": {
        "rule_type": "css-link",
        "selector": "a[href$='.exe']",
        "filter": "^((?!x64).)*$"
      },
      "x86_64": {
        "rule_type": "css-link",
        "selector": "a[href$='.x64.exe']"
      }
    },
    "version_extractor": "Vivaldi.([0-9]*(?:\\.[0-9]+)*)\\."
  },
```

**Comment by guiweber** [comment]
Yes, this will do. Thanks.

**Pull request merged**
